// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  card_section: dynamic(() => import("./CardSection")),
  contact_list: dynamic(() => import("./ContactList")),
  description: dynamic(() => import("./Description")),
  hero: dynamic(() => import("./Hero")),
};
